apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: qvrigth7g-nodejs 
  janus-idp.io/tekton: qvrigth7g-nodejs
  backstage.io/kubernetes-id: qvrigth7g-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qvrigth7g-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml